### ISSUE TITLE
Version check and output directory

### ISSUE THREAD

**Issue by songzhirui0o0** [wwylab/CliP#12]
Hi,

First of all thanks for the tool you developed. I have some suggestions:
1. In both scripts（setup.py and run_clip_main.py） there are some issues with Python version check. For example, python3.10.0 will cause unexpected errors. At this point, you need to modify the judgment logic of the subversion. 
2. Specifying the file output directory as the directory where the script is located will cause the analysis results to appear under the script directory. This doesn't cause a problem, it's just weird.

```
if not (sys.version_info[0] == 3 and sys.version_info[1] >= 5 and sys.version_info[2] >= 1):
    sys.stderr.write("Error message: CliP can only run with python >=3.5.1\n")
    sys.exit(-1)
```
```
current_dir = os.path.dirname(os.path.abspath(__file__)) # run_clip_main.py line 14

result_dir = os.path.join(current_dir, sample_id) # line 70
if not os.path.exists(result_dir):
    os.makedirs(result_dir)

path_for_preprocess = os.path.join(result_dir, args.preprocess)
path_for_preliminary = os.path.join(result_dir, "preliminary_result")
path_for_final = os.path.join(result_dir, final_result)
```

**Comment by yujie-jiang** [comment]
Hi Zhirui,

Thank you very much for your report. Regarding your first suggestion, we decided to remove the **sys.version_info[2] >= 1** so that it will allow the version check to succeed as long as the version is higher than 3.5.

For your second point, I'd like to clarify that by default, the output file will be automatically saved in a newly created folder called "final_result." As mentioned in the README file, you also have the option to modify the storage directory for the final results by using the -f flag.

Thank you again for your valuable input.

Best,
Yujie
